- name: K3os | Fetch KubeConfig
  block:
  - name: K3os | Get raw kubeconfig file
    raw: cat /etc/rancher/k3s/k3s.yaml
    register: kubeconfig_out
    changed_when: false
    retries: 10
    delay: 10
    until: kubeconfig_out.rc == 0
  - name: K3os | Store config
    ansible.builtin.set_fact:
      kubeconfig: "{{ kubeconfig_out.stdout | from_yaml }}"
  - name: K3os | Update Cluster IP
    delegate_to: localhost
    ansible.utils.update_fact:
      updates:
        - path: kubeconfig.clusters.0.cluster.server
          value: "https://{{ hostvars[ansible_play_hosts_all[0]]['ansible_host'] }}:6443"
        - path: kubeconfig.clusters.0.name
          value: "{{ cluster_name }}"
        - path: kubeconfig.contexts.0.context.cluster
          value: "{{ cluster_name }}"
        - path: kubeconfig.contexts.0.name
          value: "{{ cluster_name }}"
        - path: kubeconfig.current-context
          value: "{{ cluster_name }}"
    register: kubeconfig
  - name: K3os | Save config to file
    copy:
      content: "{{ kubeconfig.kubeconfig | to_nice_yaml }}"
      dest: "{{ kubeconfig_file }}"
    delegate_to: localhost
  - name: K3os | Save to konfig
    delegate_to: localhost
    when: konfig
    command: "kubectl konfig import --save {{ kubeconfig_file }}"
  run_once: true
  tags:
    - info
